image_dir:  /home/kyra/animl-py/examples/Southwest
working_dir: /home/kyra/animl-py/examples/Southwest
detector_file: "models/md_v1000.0.0-sorrel.onnx"
detector_type: "onnx"
classifier_file: "models/sdzwa_southwest_v3.onnx"

# file metadata
exif: True
# station_dir: None

# video processing
parallel: True
frames: 1
fps: None

# inference
device: cuda:0
checkpoint_frequency: 1000
batch_size: 4
num_workers: 4
file_col_detection: filepath
file_col_classification: filepath
class_label_col: class
empty_class: Empty # necessary for sequence classification

classifier_resize_width: 299
classifier_resize_height: 299

# sort
sort: True
copy: False

# visualization
visualize: True
